# Pipeline to publish camera sdk
name: Publish Android Camera SDK

on:
  push:
    tags:
      - 'android-camera-*'
env:
  #Github packages credentials
  NYRIS_BOT_USER: ${{ secrets.NYRIS_BOT_USER }}
  NYRIS_BOT_TAP: ${{ secrets.NYRIS_BOT_TAP }}
  LIB_VERSION_NAME: ${{ github.ref_name }}

jobs:
  gradle:
    name: Android Camera SDK Publisher
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Restore maven key
        run: |
          echo -e "${{ secrets.SIGNING_PROPERTIES }}" > signing.properties.asc
          gpg -d --passphrase ${{ secrets.GPG_KEY }} --batch signing.properties.asc > configs/signing/signing.properties
          echo -e "${{ secrets.MAVEN_KEY }}" > release-maven.asc
          gpg -d --passphrase ${{ secrets.GPG_KEY }} --batch release-maven.asc > configs/signing/release-maven.txt

      - name: Publish to Github Packages and t Maven Central
        run: ./gradlew publishCameraModulesToGithub publishCameraModulesToSonaType --no-configuration-cache