# Pipeline to publish core sdk
name: Publish Core SDK

on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  gradle-checks:
    name: KMM Pull Request checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Restore firebase key
        run: |
          echo -e "${{ secrets.FIREBASE_KEY }}" > firebase-appdist.json.asc
          gpg -d --passphrase ${{ secrets.GPG_KEY }} --batch firebase-appdist.json.asc > configs/firebase-appdist.json

      - name: Restore google services files
        run: |
          echo -e "${{ secrets.GOOGLE_SERVICES }}" > google-services.json.asc
          gpg -d --passphrase ${{ secrets.GPG_KEY }} --batch google-services.json.asc > sdk.demos/android/google-services.json

      - name: Lints and Tests
        run: ./gradlew detekt lint test --continue